dependencies:
  config:
    - paragraphs.paragraphs_type.view_reference
settings:
  handler_settings:
    target_bundles:
      view_reference: view_reference
    target_bundles_drag_drop:
      view_reference:
        weight: 0
        enabled: true