dependencies:
  config:
    - field.field.node.simplenews_issue.field_simplenews_issue_more
    - field.field.node.simplenews_issue.field_simplenews_issue_week
content:
  field_simplenews_issue_more:
    weight: 4
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: entity_reference_autocomplete
    region: content
  field_simplenews_issue_week:
    weight: 3
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: entity_reference_autocomplete
    region: content
