name: 'deGov - Social Media Settings'
description: '.'
package: deGov
type: module
core: 8.x
dependencies:
  - config_rewrite
  - degov_eu_cookie_compliance
  - degov_media_social_media_embed
  - degov_media_video

libraries:
  - degov_social_media_settings/process
