process:
  js:
    js/process.js: {}
  css:
    theme:
      css/style.css: {}
  dependencies:
    - core/jquery
    - core/drupal
    - core/drupalSettings
    - core/jquery.once
    - core/jquery.cookie
